##### [START] CATALINA HOME CONFIG IN DEVELOPMENT/ PRODUCTION [/START] ########
## Note: ENABLE THIS ONLY IN CASE OF EMBEDDED TOMCAT DEPLOYMENT  ###
######___ ***** ENTER PATH TO YOUR STAND-ALONE TOMCAT SERVER ***** ____ ############

catalina:
  home: /Users/bijayshrestha/Dropbox/Workspaces/Backend/tomcat

##### [END] CATALINA HOME CONFIG [/END] #########

spring:
  profiles:
    active: dev