catalina:
  home: /Users/bijayshrestha/Dropbox/Workspaces/Backend/tomcat

server:
  port: 9090
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:mysql://10.13.194.238:3308/spring-boot-yaml?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: fonebank
    password: fonebank
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      generate_statistics: true
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
    open-in-view: false

  jackson:
    deserialization.fail-on-unknown-properties: false

  minio:
    url: http://uat-presigned.cogenthealth.com.np
    bucket: cogent-appointment
    access-key: cogent-appointment
    secret-key: cogentappointment@123

entitymanager:
  packages:
    to:
      scan: com.cogent.cogentappointment.persistence.model